                            
/pausar: pausar.o
        gcc -o  pausar  pausar.o
pausar.o: pausar.s 
        as  -o pausar.o pausar.s
clean:
        rm pausar pausar.o
        rm primos primos.o
        rm stack stack.o
        rm teclado teclado.o
        rm torre torre.o
 

primos: primos.o
        gcc -o  primos primos.o
primos.o: primos.s 
        as  -o primos.o primos.s
        

stack: stack.o
        gcc -o  stack stack.o
stack.o: stack.s 
        as  -o stack.o stack.s
        

teclado: teclado.o
        gcc -o  teclado teclado.o
teclado.o: teclado.s 
        as  -o teclado.o teclado.s
        
torre: torre.o
        gcc -o  torre torre.o
torre.o: torre.s 
        as  -o torre.o torre.s
